data:
  #args forwarded (linked) to model
  dataset_name: rainfall
  num_input_steps: 2
  num_pred_steps_train: 1
  num_pred_steps_val_test: 3
  batch_size: 1

  #other args
  num_workers: 10
  prefetch_factor: null
  pin_memory: False
  dataset_conf:
    periods:
      train:
        start: 20200101
        end: 20230101
        obs_step: 300
        obs_step_btw_t0: 10800
      valid:
        start: 20230101
        end: 20240101
        obs_step: 300
        obs_step_btw_t0: 10800
      test:
        start: 20240101
        end: 20250101
        obs_step: 300
        obs_step_btw_t0: 10800
    grid:
      name: 
      border_size: 0
      proj_name: Stereographic
      projection_kwargs:
        central_latitude: 45
    settings:
      standardize: true
      file_format: npz
    params:
      precip:
        levels: [0]
        typeOfLevel: surface
        kind: input_output